In [1]:
import numpy as np

In [3]:
data = np.ones((3,5))
print(data)
print(data.ndim,data.dtype,data.shape)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
2 float64 (3, 5)


In [22]:
data1 = np.zeros((3,5))
data1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
data = np.arange(2,6)
data

array([2, 3, 4, 5])

In [30]:
data2 = np.concatenate([data,data1])
data2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [29]:
data2 = data2.astype(np.uint16)
data2

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=uint16)

In [34]:
data3 = np.zeros_like(data2,dtype=np.uint16)
data3

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=uint16)

In [36]:
data4 = np.random.random((10,3))
data4

array([[0.22085   , 0.73888379, 0.30632782],
       [0.45962307, 0.64161968, 0.06254412],
       [0.31360896, 0.12881273, 0.85027529],
       [0.08428656, 0.00256927, 0.41064315],
       [0.07793969, 0.09852785, 0.61277716],
       [0.77455274, 0.47448049, 0.73867893],
       [0.34293852, 0.47292267, 0.10005452],
       [0.13828031, 0.02188885, 0.42833337],
       [0.36223549, 0.16548089, 0.71562377],
       [0.37779923, 0.74122848, 0.8114568 ]])

In [37]:
#we cannot combine two arrays of different shapes
data5 = data4 + data3
data5

ValueError: operands could not be broadcast together with shapes (10,3) (6,5) 

In [4]:
data = np.ones((3,5))
data

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
data.reshape(5,3)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [50]:
data.ravel()

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [52]:
data.flatten()

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [57]:
data = np.ones((2,3))
data1 = np.zeros((2,3))
print(data,data1)

[[1. 1. 1.]
 [1. 1. 1.]] [[0. 0. 0.]
 [0. 0. 0.]]


In [63]:
print(np.concatenate((data,data1)))
print(np.hstack((data,data1)))
print(np.vstack((data,data1)))

[[1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
data = np.arange(20).reshape(5,4)
print(data)
print(data.transpose())
print(data.T)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[ 0  4  8 12 16]
 [ 1  5  9 13 17]
 [ 2  6 10 14 18]
 [ 3  7 11 15 19]]
[[ 0  4  8 12 16]
 [ 1  5  9 13 17]
 [ 2  6 10 14 18]
 [ 3  7 11 15 19]]


In [25]:
a = np.array(((1,2),(3,4)))
b = np.array(((1,2),(3,4)))
a *= b
a

array([[ 1,  4],
       [ 9, 16]])

In [44]:
c = np.array(((4,9),(16,25)))
np.max(c)
np.dot()

25

In [123]:
np.linalg.det(a)

-8.000000000000002